import type { Listing, User } from './types';

/** Public sample MP4s (Google / Pexels CDN) for demo video listings. */
export const SAMPLE_VIDEOS = [
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
] as const;

/** Fashion photography — Unsplash HTTPS (stable image IDs). */
const img = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const SEED_USERS: User[] = [
  {
    id: 'u_demo',
    email: 'demo@rota.app',
    handle: 'demo.rota',
    name: 'Demo Rota',
    city: 'Paris',
    bio: 'Closet fondateur · Marais',
    avatarUrl: img('photo-1534528741775-53994a69daeb', 200),
    certified: true,
    foundingCloset: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'u_camille',
    email: 'camille@rota.app',
    handle: 'camille.b',
    name: 'Camille B.',
    city: 'Paris',
    bio: 'Soie & archives · 11e',
    avatarUrl: img('photo-1524504388940-b1c1722653e1', 200),
    certified: true,
    foundingCloset: true,
    createdAt: '2026-02-01T00:00:00.000Z',
  },
  {
    id: 'u_yasmine',
    email: 'yasmine@rota.app',
    handle: 'yasmine.k',
    name: 'Yasmine K.',
    city: 'Paris',
    bio: 'Cuir vintage · Lyon → Paris',
    avatarUrl: img('photo-1494790108377-be9c29b29330', 200),
    certified: false,
    foundingCloset: true,
    createdAt: '2026-02-10T00:00:00.000Z',
  },
  {
    id: 'u_juliette',
    email: 'juliette@rota.app',
    handle: 'juliette.m',
    name: 'Juliette M.',
    city: 'Paris',
    bio: 'Gala & sequins · 9e',
    avatarUrl: img('photo-1517841905240-472988babdf9', 200),
    certified: true,
    foundingCloset: true,
    createdAt: '2026-03-01T00:00:00.000Z',
  },
  {
    id: 'u_lea',
    email: 'lea@rota.app',
    handle: 'lea.m',
    name: 'Léa M.',
    city: 'Paris',
    bio: 'Tailoring 90s · Bastille',
    avatarUrl: img('photo-1438761681033-6461ffad8d80', 200),
    certified: false,
    foundingCloset: false,
    createdAt: '2026-03-15T00:00:00.000Z',
  },
  {
    id: 'u_manon',
    email: 'manon@rota.app',
    handle: 'manon.l',
    name: 'Manon L.',
    city: 'Paris',
    bio: 'Perles & soirée · 6e',
    avatarUrl: img('photo-1544005313-94ddf0286df2', 200),
    certified: true,
    foundingCloset: true,
    createdAt: '2026-04-01T00:00:00.000Z',
  },
];

export const SEED_LISTINGS: Omit<Listing, 'createdAt'>[] = [
  {
    id: 'f1',
    ownerId: 'u_camille',
    title: 'Nuisette en biais, ivoire',
    brand: 'Réalisation Par',
    description: 'Soie biaisée, coupe fluide. Idéale dîner ou weekend. Retour dans la housse fournie.',
    pricePerDay: 24,
    retail: 340,
    size: 'S',
    category: 'Soirée',
    occasion: 'Dîner',
    city: 'Paris',
    neighborhood: 'Paris 11e',
    media: [
      { url: img('photo-1595777457583-95e059d581b8'), kind: 'image' },
      { url: img('photo-1566174053879-31528523f8ae'), kind: 'image' },
      { url: SAMPLE_VIDEOS[0], kind: 'video', poster: img('photo-1595777457583-95e059d581b8', 400) },
    ],
    badge: 'Réservation immédiate',
    wornCount: 9,
    rating: 4.9,
    authenticity: 'receipt',
    cleaningByLender: false,
    cleaningFee: 0,
    rules: [
      'Lavage à la main uniquement, eau froide',
      'Pas de parfum ni de cigarette sur le tissu',
      'Retour dans la housse fournie',
    ],
    instantBook: true,
    likes: 12400,
  },
  {
    id: 'f2',
    ownerId: 'u_yasmine',
    title: 'Trench en cuir vintage',
    brand: "Pièce d'archive",
    description: 'Cuir souple années 90. Ne pas laver — nettoyage par mes soins.',
    pricePerDay: 31,
    retail: 620,
    size: 'M',
    category: 'Manteaux',
    occasion: 'Tous les jours',
    city: 'Paris',
    neighborhood: 'Paris 3e',
    media: [
      { url: img('photo-1551028719-00167b16eac5'), kind: 'image' },
      { url: img('photo-1521223890158-f9f7c3d5d504'), kind: 'image' },
    ],
    badge: 'Livraison offerte',
    wornCount: 23,
    rating: 5.0,
    authenticity: 'tag',
    cleaningByLender: true,
    cleaningFee: 14,
    rules: ['Ne pas laver : cuir nettoyé par mes soins', 'Pas de pluie prolongée'],
    instantBook: false,
    likes: 8100,
  },
  {
    id: 'f3',
    ownerId: 'u_juliette',
    title: 'Robe colonne à sequins',
    brand: 'Rasario',
    description: 'Robe colonne pour gala. Pressing spécialisé inclus.',
    pricePerDay: 58,
    retail: 1480,
    size: 'S–M',
    category: 'Robes',
    occasion: 'Gala',
    city: 'Paris',
    neighborhood: 'Paris 9e',
    media: [
      { url: img('photo-1566174053879-31528523f8ae'), kind: 'image' },
      { url: img('photo-1515372039744-b8f02a3ae446'), kind: 'image' },
      { url: SAMPLE_VIDEOS[1], kind: 'video', poster: img('photo-1566174053879-31528523f8ae', 400) },
    ],
    badge: 'Créateur',
    wornCount: 4,
    rating: 4.96,
    authenticity: 'receipt',
    cleaningByLender: true,
    cleaningFee: 18,
    rules: [
      'Ne pas laver ni repasser : pressing spécialisé à mes frais',
      'Pas de maquillage sur le col',
      'Retour sous 48 h après la date de fin',
    ],
    instantBook: true,
    likes: 31200,
  },
  {
    id: 'f4',
    ownerId: 'u_lea',
    title: 'Blazer en velours, prune',
    brand: 'Ganni',
    description: 'Blazer oversize en velours. Parfait bureau ou afterwork.',
    pricePerDay: 19,
    retail: 295,
    size: 'S',
    category: 'Tailoring',
    occasion: 'Entretien',
    city: 'Paris',
    neighborhood: 'Paris 11e',
    media: [
      { url: img('photo-1591369822096-ffd140ec948f'), kind: 'image' },
      { url: img('photo-1594938298603-c8148c4dae35'), kind: 'image' },
    ],
    badge: 'Prix baissé',
    wornCount: 11,
    rating: 4.8,
    authenticity: 'receipt',
    cleaningByLender: false,
    cleaningFee: 0,
    rules: ['Pas de déodorant blanc', 'Repassage vapeur OK'],
    instantBook: true,
    likes: 2100,
  },
  {
    id: 'f5',
    ownerId: 'u_manon',
    title: 'Mini robe perlée, jais',
    brand: 'Self-Portrait',
    description: 'Perles noires, coupe mini. Soirée ou cocktail.',
    pricePerDay: 41,
    retail: 890,
    size: 'M',
    category: 'Robes',
    occasion: 'Soirée',
    city: 'Paris',
    neighborhood: 'Paris 6e',
    media: [
      { url: img('photo-1572804013309-59a88b7e92f1'), kind: 'image' },
      { url: img('photo-1496747611176-843222e1e57c'), kind: 'image' },
      { url: SAMPLE_VIDEOS[2], kind: 'video', poster: img('photo-1572804013309-59a88b7e92f1', 400) },
    ],
    badge: 'Livraison offerte',
    wornCount: 7,
    rating: 4.85,
    authenticity: 'receipt',
    cleaningByLender: true,
    cleaningFee: 12,
    rules: ['Pas de talons pointus sur ourlet', 'Retour sous housse'],
    instantBook: true,
    likes: 5600,
  },
  {
    id: 'f6',
    ownerId: 'u_camille',
    title: 'Top résille manches longues',
    brand: 'Acne Studios',
    description: 'Résille noire semi-transparente. À superposer.',
    pricePerDay: 14,
    retail: 180,
    size: 'XS',
    category: 'Soirée',
    occasion: 'Festival',
    city: 'Paris',
    neighborhood: 'Paris 11e',
    media: [
      { url: img('photo-1483985988355-763728e1935b'), kind: 'image' },
      { url: img('photo-1469334031218-e382a71b716b'), kind: 'image' },
    ],
    wornCount: 15,
    rating: 4.7,
    authenticity: null,
    cleaningByLender: false,
    cleaningFee: 0,
    rules: ['Lavage délicat', 'Pas de bijoux accrochants'],
    instantBook: true,
    likes: 3400,
  },
  {
    id: 'f7',
    ownerId: 'u_yasmine',
    title: 'Manteau en laine, camel',
    brand: 'Max Mara',
    description: 'Manteau camel classique. Chaleur et ligne nette.',
    pricePerDay: 27,
    retail: 1100,
    size: 'L',
    category: 'Manteaux',
    occasion: 'Tous les jours',
    city: 'Paris',
    neighborhood: 'Paris 8e',
    media: [
      { url: img('photo-1539533018447-63fcce2678e3'), kind: 'image' },
      { url: img('photo-1548624313-0396c75e4b1a'), kind: 'image' },
    ],
    badge: 'Au plus près',
    wornCount: 5,
    rating: 4.95,
    authenticity: 'receipt',
    cleaningByLender: true,
    cleaningFee: 16,
    rules: ['Pressing uniquement', 'Pas de pluie'],
    instantBook: false,
    likes: 4200,
  },
  {
    id: 'f8',
    ownerId: 'u_juliette',
    title: 'Robe à plumes, champagne',
    brand: '16Arlington',
    description: 'Plumes délicates — manipulation soigneuse obligatoire.',
    pricePerDay: 47,
    retail: 1250,
    size: 'S',
    category: 'Robes',
    occasion: 'Mariage',
    city: 'Paris',
    neighborhood: 'Paris 16e',
    media: [
      { url: img('photo-1596783074918-c84cb065579e'), kind: 'image' },
      { url: img('photo-1585487000160-6ebcfceb0d03'), kind: 'image' },
    ],
    badge: 'Créateur',
    wornCount: 3,
    rating: 5.0,
    authenticity: 'receipt',
    cleaningByLender: true,
    cleaningFee: 22,
    rules: ['Ne pas s’asseoir sur les plumes', 'Transport en housse rigide'],
    instantBook: true,
    likes: 9800,
  },
  {
    id: 'f9',
    ownerId: 'u_lea',
    title: 'Jean droit archive, indigo',
    brand: 'Helmut Lang',
    description: 'Denim d’archive coupe droite. Patine naturelle.',
    pricePerDay: 16,
    retail: 420,
    size: 'M',
    category: 'Vintage',
    occasion: 'Festival',
    city: 'Paris',
    neighborhood: 'Paris 10e',
    media: [
      { url: img('photo-1541099649105-f69ad21f3246'), kind: 'image' },
      { url: img('photo-1582418702059-97ebafb35d09'), kind: 'image' },
    ],
    wornCount: 18,
    rating: 4.6,
    authenticity: 'tag',
    cleaningByLender: false,
    cleaningFee: 0,
    rules: ['Pas de lessive agressive', 'Retour propre'],
    instantBook: true,
    likes: 1900,
  },
  {
    id: 'f10',
    ownerId: 'u_manon',
    title: 'Sac baguette satin, noir',
    brand: 'The Row',
    description: 'Petit sac soirée. Chaîne dorée amovible.',
    pricePerDay: 22,
    retail: 980,
    size: 'Unique',
    category: 'Sacs',
    occasion: 'Dîner',
    city: 'Paris',
    neighborhood: 'Paris 7e',
    media: [
      { url: img('photo-1584917865442-de89df76afd3'), kind: 'image' },
      { url: img('photo-1566150905458-1bf1fc113f0d'), kind: 'image' },
    ],
    badge: 'Réservation immédiate',
    wornCount: 12,
    rating: 4.9,
    authenticity: 'receipt',
    cleaningByLender: false,
    cleaningFee: 0,
    rules: ['Pas de liquides dans le sac', 'Retour avec dustbag'],
    instantBook: true,
    likes: 6700,
  },
  {
    id: 'f11',
    ownerId: 'u_camille',
    title: 'Sandales à talon, nude',
    brand: 'Amina Muaddi',
    description: 'Pointure 38. Talon 10 cm. Semelle impeccable.',
    pricePerDay: 28,
    retail: 650,
    size: '38',
    category: 'Chaussures',
    occasion: 'Gala',
    city: 'Paris',
    neighborhood: 'Paris 11e',
    media: [
      { url: img('photo-1543163521-1bf539c55dd2'), kind: 'image' },
      { url: img('photo-1515347619252-60a4bf4fff4f'), kind: 'image' },
    ],
    wornCount: 6,
    rating: 4.88,
    authenticity: 'receipt',
    cleaningByLender: false,
    cleaningFee: 0,
    rules: ['Semelles propres au retour', 'Pas de pluie'],
    instantBook: true,
    likes: 5100,
  },
  {
    id: 'f12',
    ownerId: 'u_demo',
    title: 'Veste en tweed courte',
    brand: 'Chanel-inspired archive',
    description: 'Tweed rose pâle. Pièce closet fondateur Rota.',
    pricePerDay: 32,
    retail: 780,
    size: 'S',
    category: 'Tailoring',
    occasion: 'Bureau',
    city: 'Paris',
    neighborhood: 'Paris 4e',
    media: [
      { url: img('photo-1591047139829-d91aecb6caea'), kind: 'image' },
      { url: img('photo-1551488831-00ddcb6c6bd3'), kind: 'image' },
    ],
    badge: 'Closet fondateur',
    wornCount: 6,
    rating: 4.92,
    authenticity: 'receipt',
    cleaningByLender: true,
    cleaningFee: 10,
    rules: ['Pressing recommandé', 'Pas de broches lourdes'],
    instantBook: true,
    likes: 2800,
  },
];

export const FEES = {
  shipping: 9,
  cover: 8,
  deposit: 150,
  commission: 0.12,
  latePerDay: 20,
} as const;

export const CATEGORIES = [
  'Robes',
  'Manteaux',
  'Tailoring',
  'Soirée',
  'Chaussures',
  'Sacs',
  'Vintage',
] as const;

export const OCCASIONS = [
  'Gala',
  'Mariage',
  'Tous les jours',
  'Festival',
  'Entretien',
  'Dîner',
  'Soirée',
  'Bureau',
] as const;
